/**
 * @module
 * WARNING: This file is modified by builders
 */

/**
 * Extracts an array of intercepted resource types
 * @returns {array} An array of type resource strings
 */
const interceptedTypes = [
  'script',
  'image',
  'stylesheet',
  /* <auto-generated-content> */
];

export { interceptedTypes };
